### ISSUE TITLE
Replicated Icons

### ISSUE THREAD

**Issue by jsiko11** [moodlehq/moodle-local_mobile#25]
Hi Juan,

Today I'm testing the module with differents users at the same Moodle Site.
There is a problem when you switch from one user to other, the icons get replicated recursively unless you clean cache manually.

![captura](https://cloud.githubusercontent.com/assets/6874953/11212082/d0748862-8d33-11e5-8f01-895ae7c09dad.PNG)

**Comment by dpalou** [comment]
Hi jsiko,

we just integrated a fix to prevent duplicated addons in My Courses. The behaviour we saw wasn't the one that you're describing, but it's possible that the fix also works for your problem. 

If you tested it using the Moodle Mobile app from the stores you'll have it fixed in the next release. If you built your own version using GitHub code then you can update your code and test it since the fix is already integrated in https://github.com/moodlehq/moodlemobile2/.

I'll leave this issue open until you verify that it's fixed :)

Kind regards,
Dani

**Comment by dpalou** [comment]
Oh, I just realised this comment is on local_mobile repository, I think this issue should be in the Moodle Mobile repository, not in local_mobile.
